In [1]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.3.0-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from xgboost) (1.15.3)
Downloading xgboost-3.3.0-py3-none-win_amd64.whl (69.5 MB)
   ---------------------------------------- 0.0/69.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/69.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/69.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/69.5 MB ? eta -:--:--
    --------------------------------------- 1.0/69.5 MB 2.6 MB/s eta 0:00:27
   - -------------------------------------- 1.8/69.5 MB 3.3 MB/s eta 0:00:21
   - -------------------------------------- 1.8/69.5 MB 3.3 MB/s eta 0:00:21
   - -------------------------------------- 2.6/69.5 MB 2.5 MB/s eta 0:00:27
   - -------------------------------------- 2.9/69.5 MB 2.4 MB/s eta 0:00:29
   -- ------------------------------------- 3.7/69.5 MB 2.5 MB/s eta 0:00:27
   -- ------------------------------------- 3.9/69.5 MB 2.4 MB/s eta 0:00:28
   -- ------------------------------------- 3.9/69.5 MB 2.4 MB/s eta 0:00:28
   -- ------------------------------------- 4.5/69.5 MB 2.1 MB/s eta 0:00:32
   -- ------------------------------------- 5.0/69.5 MB 2.2 MB/s eta 0:00:29
   --- ------------------------------------ 5.5/69.5 MB 2.1 MB/s eta 0:00:31
   --- ------------------------------------ 5.8/69.5 MB 2.1 MB/s eta 0:00:31
   --- ------------------------------------ 6.3/69.5 MB 2.1 MB/s eta 0:00:31
   --- ------------------------------------ 6.6/69.5 MB 2.1 MB/s eta 0:00:31
   --- ------------------------------------ 6.8/69.5 MB 2.0 MB/s eta 0:00:31
   ---- ----------------------------------- 7.1/69.5 MB 1.9 MB/s eta 0:00:33
   ---- ----------------------------------- 7.3/69.5 MB 1.9 MB/s eta 0:00:34
   ---- ----------------------------------- 7.3/69.5 MB 1.9 MB/s eta 0:00:34
   ---- ----------------------------------- 7.6/69.5 MB 1.8 MB/s eta 0:00:34
   ---- ----------------------------------- 7.9/69.5 MB 1.8 MB/s eta 0:00:35
   ---- ----------------------------------- 8.1/69.5 MB 1.8 MB/s eta 0:00:36
   ---- ----------------------------------- 8.4/69.5 MB 1.7 MB/s eta 0:00:36
   ---- ----------------------------------- 8.7/69.5 MB 1.7 MB/s eta 0:00:36
   ----- ---------------------------------- 8.9/69.5 MB 1.7 MB/s eta 0:00:37
   ----- ---------------------------------- 9.2/69.5 MB 1.6 MB/s eta 0:00:37
   ----- ---------------------------------- 9.4/69.5 MB 1.6 MB/s eta 0:00:38
   ----- ---------------------------------- 9.4/69.5 MB 1.6 MB/s eta 0:00:38
   ----- ---------------------------------- 9.7/69.5 MB 1.6 MB/s eta 0:00:38
   ----- ---------------------------------- 10.0/69.5 MB 1.6 MB/s eta 0:00:38
   ----- ---------------------------------- 10.2/69.5 MB 1.6 MB/s eta 0:00:38
   ------ --------------------------------- 10.5/69.5 MB 1.6 MB/s eta 0:00:39
   ------ --------------------------------- 10.7/69.5 MB 1.5 MB/s eta 0:00:39
   ------ --------------------------------- 11.0/69.5 MB 1.5 MB/s eta 0:00:39
   ------ --------------------------------- 11.3/69.5 MB 1.5 MB/s eta 0:00:39
   ------ --------------------------------- 11.5/69.5 MB 1.5 MB/s eta 0:00:39
   ------ --------------------------------- 11.8/69.5 MB 1.5 MB/s eta 0:00:39
   ------ --------------------------------- 12.1/69.5 MB 1.5 MB/s eta 0:00:39
   ------- -------------------------------- 12.3/69.5 MB 1.5 MB/s eta 0:00:39
   ------- -------------------------------- 12.6/69.5 MB 1.5 MB/s eta 0:00:39
   ------- -------------------------------- 12.8/69.5 MB 1.5 MB/s eta 0:00:39
   ------- -------------------------------- 13.1/69.5 MB 1.4 MB/s eta 0:00:39
   ------- -------------------------------- 13.4/69.5 MB 1.4 MB/s eta 0:00:39
   ------- -------------------------------- 13.6/69.5 MB 1.4 MB/s eta 0:00:39
   ------- -------------------------------- 13.9/69.5 MB 1.4 MB/s eta 0:00:39
   -------- ------------------------------- 14.2/69.5 MB 1.4 MB/s eta 0:00:39
   -------- ------------------------------- 14.4/69.5 MB 1.4 MB/s eta 0:00:39
   -------- ------------------------------- 14.7/69.5 MB 1.4 MB/s eta 0:00:39
   -------- ------------------------------- 14.9/69.5 MB 1.4 MB/s eta 0:00:39
   -------- ------------------------------- 15.2/69.5 MB 1.4 MB/s eta 0:00:39
   -------- ------------------------------- 15.5/69.5 MB 1.4 MB/s eta 0:00:39
   --------- ------------------------------ 15.7/69.5 MB 1.4 MB/s eta 0:00:39
   --------- ------------------------------ 16.0/69.5 MB 1.4 MB/s eta 0:00:38
   --------- ------------------------------ 16.3/69.5 MB 1.4 MB/s eta 0:00:38
   --------- ------------------------------ 16.8/69.5 MB 1.4 MB/s eta 0:00:38
   --------- ------------------------------ 17.0/69.5 MB 1.4 MB/s eta 0:00:38
   --------- ------------------------------ 17.3/69.5 MB 1.4 MB/s eta 0:00:37
   ---------- ----------------------------- 17.8/69.5 MB 1.4 MB/s eta 0:00:37
   ---------- ----------------------------- 18.1/69.5 MB 1.4 MB/s eta 0:00:37
   ---------- ----------------------------- 18.4/69.5 MB 1.4 MB/s eta 0:00:36
   ---------- ----------------------------- 18.9/69.5 MB 1.4 MB/s eta 0:00:36
   ----------- ---------------------------- 19.4/69.5 MB 1.5 MB/s eta 0:00:35
   ----------- ---------------------------- 19.7/69.5 MB 1.5 MB/s eta 0:00:35
   ----------- ---------------------------- 20.2/69.5 MB 1.5 MB/s eta 0:00:34
   ----------- ---------------------------- 20.7/69.5 MB 1.5 MB/s eta 0:00:33
   ------------ --------------------------- 21.2/69.5 MB 1.5 MB/s eta 0:00:33
   ------------ --------------------------- 21.8/69.5 MB 1.5 MB/s eta 0:00:32
   ------------ --------------------------- 22.0/69.5 MB 1.5 MB/s eta 0:00:32
   ------------ --------------------------- 22.5/69.5 MB 1.5 MB/s eta 0:00:31
   ------------- -------------------------- 23.1/69.5 MB 1.5 MB/s eta 0:00:31
   ------------- -------------------------- 23.3/69.5 MB 1.5 MB/s eta 0:00:31
   ------------- -------------------------- 23.6/69.5 MB 1.5 MB/s eta 0:00:31
   ------------- -------------------------- 23.9/69.5 MB 1.5 MB/s eta 0:00:30
   ------------- -------------------------- 24.1/69.5 MB 1.5 MB/s eta 0:00:30
   -------------- ------------------------- 24.4/69.5 MB 1.5 MB/s eta 0:00:30
   -------------- ------------------------- 24.9/69.5 MB 1.5 MB/s eta 0:00:30
   -------------- ------------------------- 25.2/69.5 MB 1.5 MB/s eta 0:00:30
   -------------- ------------------------- 25.4/69.5 MB 1.5 MB/s eta 0:00:29
   -------------- ------------------------- 25.7/69.5 MB 1.5 MB/s eta 0:00:29
   --------------- ------------------------ 26.2/69.5 MB 1.5 MB/s eta 0:00:29
   --------------- ------------------------ 26.5/69.5 MB 1.5 MB/s eta 0:00:29
   --------------- ------------------------ 26.7/69.5 MB 1.5 MB/s eta 0:00:29
   --------------- ------------------------ 27.3/69.5 MB 1.5 MB/s eta 0:00:28
   --------------- ------------------------ 27.5/69.5 MB 1.5 MB/s eta 0:00:28
   --------------- ------------------------ 27.8/69.5 MB 1.5 MB/s eta 0:00:28
   ---------------- ----------------------- 28.0/69.5 MB 1.5 MB/s eta 0:00:28
   ---------------- ----------------------- 28.6/69.5 MB 1.5 MB/s eta 0:00:27
   ---------------- ----------------------- 28.8/69.5 MB 1.5 MB/s eta 0:00:27
   ---------------- ----------------------- 29.1/69.5 MB 1.5 MB/s eta 0:00:27
   ----------------- ---------------------- 29.6/69.5 MB 1.5 MB/s eta 0:00:27
   ----------------- ---------------------- 29.9/69.5 MB 1.5 MB/s eta 0:00:26
   ----------------- ---------------------- 30.1/69.5 MB 1.5 MB/s eta 0:00:26
   ----------------- ---------------------- 30.7/69.5 MB 1.5 MB/s eta 0:00:26
   ----------------- ---------------------- 30.9/69.5 MB 1.5 MB/s eta 0:00:26
   ----------------- ---------------------- 31.2/69.5 MB 1.5 MB/s eta 0:00:25
   ------------------ --------------------- 31.7/69.5 MB 1.5 MB/s eta 0:00:25
   ------------------ --------------------- 32.0/69.5 MB 1.5 MB/s eta 0:00:25
   ------------------ --------------------- 32.2/69.5 MB 1.5 MB/s eta 0:00:25
   ------------------ --------------------- 32.5/69.5 MB 1.5 MB/s eta 0:00:25
   ------------------- -------------------- 33.0/69.5 MB 1.5 MB/s eta 0:00:24
   ------------------- -------------------- 33.3/69.5 MB 1.5 MB/s eta 0:00:24
   ------------------- -------------------- 33.8/69.5 MB 1.5 MB/s eta 0:00:24
   ------------------- -------------------- 34.1/69.5 MB 1.5 MB/s eta 0:00:23
   ------------------- -------------------- 34.3/69.5 MB 1.5 MB/s eta 0:00:23
   -------------------- ------------------- 34.9/69.5 MB 1.5 MB/s eta 0:00:23
   -------------------- ------------------- 35.1/69.5 MB 1.6 MB/s eta 0:00:23
   -------------------- ------------------- 35.7/69.5 MB 1.6 MB/s eta 0:00:22
   -------------------- ------------------- 35.9/69.5 MB 1.6 MB/s eta 0:00:22
   -------------------- ------------------- 36.4/69.5 MB 1.6 MB/s eta 0:00:22
   --------------------- ------------------ 36.7/69.5 MB 1.6 MB/s eta 0:00:22
   --------------------- ------------------ 37.2/69.5 MB 1.6 MB/s eta 0:00:21
   --------------------- ------------------ 37.5/69.5 MB 1.6 MB/s eta 0:00:21
   --------------------- ------------------ 38.0/69.5 MB 1.6 MB/s eta 0:00:21
   ---------------------- ----------------- 38.5/69.5 MB 1.6 MB/s eta 0:00:20
   ---------------------- ----------------- 38.8/69.5 MB 1.6 MB/s eta 0:00:20
   ---------------------- ----------------- 39.3/69.5 MB 1.6 MB/s eta 0:00:20
   ---------------------- ----------------- 39.8/69.5 MB 1.6 MB/s eta 0:00:19
   ----------------------- ---------------- 40.4/69.5 MB 1.6 MB/s eta 0:00:19
   ----------------------- ---------------- 40.9/69.5 MB 1.6 MB/s eta 0:00:18
   ----------------------- ---------------- 41.2/69.5 MB 1.6 MB/s eta 0:00:18
   ----------------------- ---------------- 41.7/69.5 MB 1.6 MB/s eta 0:00:18
   ------------------------ --------------- 42.2/69.5 MB 1.6 MB/s eta 0:00:17
   ------------------------ --------------- 42.5/69.5 MB 1.6 MB/s eta 0:00:17
   ------------------------ --------------- 42.7/69.5 MB 1.6 MB/s eta 0:00:17
   ------------------------ --------------- 42.7/69.5 MB 1.6 MB/s eta 0:00:17
   ------------------------ --------------- 43.0/69.5 MB 1.6 MB/s eta 0:00:17
   ------------------------ --------------- 43.3/69.5 MB 1.6 MB/s eta 0:00:17
   ------------------------- -------------- 43.5/69.5 MB 1.6 MB/s eta 0:00:17
   ------------------------- -------------- 43.8/69.5 MB 1.6 MB/s eta 0:00:17
   ------------------------- -------------- 44.0/69.5 MB 1.6 MB/s eta 0:00:17
   ------------------------- -------------- 44.3/69.5 MB 1.6 MB/s eta 0:00:16
   ------------------------- -------------- 44.3/69.5 MB 1.6 MB/s eta 0:00:16
   ------------------------- -------------- 44.6/69.5 MB 1.6 MB/s eta 0:00:16
   ------------------------- -------------- 44.8/69.5 MB 1.6 MB/s eta 0:00:16
   ------------------------- -------------- 45.1/69.5 MB 1.6 MB/s eta 0:00:16
   -------------------------- ------------- 45.4/69.5 MB 1.6 MB/s eta 0:00:16
   -------------------------- ------------- 45.6/69.5 MB 1.6 MB/s eta 0:00:16
   -------------------------- ------------- 45.9/69.5 MB 1.6 MB/s eta 0:00:16
   -------------------------- ------------- 46.1/69.5 MB 1.6 MB/s eta 0:00:16
   -------------------------- ------------- 46.4/69.5 MB 1.5 MB/s eta 0:00:15
   -------------------------- ------------- 46.7/69.5 MB 1.5 MB/s eta 0:00:15
   -------------------------- ------------- 46.9/69.5 MB 1.5 MB/s eta 0:00:15
   --------------------------- ------------ 47.2/69.5 MB 1.5 MB/s eta 0:00:15
   --------------------------- ------------ 47.2/69.5 MB 1.5 MB/s eta 0:00:15
   --------------------------- ------------ 47.4/69.5 MB 1.5 MB/s eta 0:00:15
   --------------------------- ------------ 47.7/69.5 MB 1.5 MB/s eta 0:00:15
   --------------------------- ------------ 48.0/69.5 MB 1.5 MB/s eta 0:00:15
   --------------------------- ------------ 48.2/69.5 MB 1.5 MB/s eta 0:00:15
   --------------------------- ------------ 48.5/69.5 MB 1.5 MB/s eta 0:00:15
   ---------------------------- ----------- 48.8/69.5 MB 1.5 MB/s eta 0:00:15
   ---------------------------- ----------- 49.0/69.5 MB 1.5 MB/s eta 0:00:14
   ---------------------------- ----------- 49.3/69.5 MB 1.5 MB/s eta 0:00:14
   ---------------------------- ----------- 49.5/69.5 MB 1.5 MB/s eta 0:00:14
   ---------------------------- ----------- 49.8/69.5 MB 1.5 MB/s eta 0:00:14
   ---------------------------- ----------- 50.1/69.5 MB 1.5 MB/s eta 0:00:14
   ---------------------------- ----------- 50.3/69.5 MB 1.5 MB/s eta 0:00:14
   ----------------------------- ---------- 50.6/69.5 MB 1.5 MB/s eta 0:00:14
   ----------------------------- ---------- 50.9/69.5 MB 1.5 MB/s eta 0:00:13
   ----------------------------- ---------- 51.1/69.5 MB 1.5 MB/s eta 0:00:13
   ----------------------------- ---------- 51.4/69.5 MB 1.5 MB/s eta 0:00:13
   ----------------------------- ---------- 51.6/69.5 MB 1.5 MB/s eta 0:00:13
   ----------------------------- ---------- 51.9/69.5 MB 1.5 MB/s eta 0:00:13
   ------------------------------ --------- 52.4/69.5 MB 1.5 MB/s eta 0:00:12
   ------------------------------ --------- 52.7/69.5 MB 1.5 MB/s eta 0:00:12
   ------------------------------ --------- 53.0/69.5 MB 1.5 MB/s eta 0:00:12
   ------------------------------ --------- 53.5/69.5 MB 1.5 MB/s eta 0:00:11
   ------------------------------ --------- 53.7/69.5 MB 1.5 MB/s eta 0:00:11
   ------------------------------- -------- 54.0/69.5 MB 1.5 MB/s eta 0:00:11
   ------------------------------- -------- 54.5/69.5 MB 1.5 MB/s eta 0:00:11
   ------------------------------- -------- 55.1/69.5 MB 1.5 MB/s eta 0:00:10
   ------------------------------- -------- 55.3/69.5 MB 1.5 MB/s eta 0:00:10
   -------------------------------- ------- 55.8/69.5 MB 1.5 MB/s eta 0:00:10
   -------------------------------- ------- 56.4/69.5 MB 1.5 MB/s eta 0:00:09
   -------------------------------- ------- 56.9/69.5 MB 1.5 MB/s eta 0:00:09
   --------------------------------- ------ 57.4/69.5 MB 1.5 MB/s eta 0:00:08
   --------------------------------- ------ 57.9/69.5 MB 1.5 MB/s eta 0:00:08
   --------------------------------- ------ 58.2/69.5 MB 1.5 MB/s eta 0:00:08
   --------------------------------- ------ 58.5/69.5 MB 1.6 MB/s eta 0:00:08
   --------------------------------- ------ 58.7/69.5 MB 1.6 MB/s eta 0:00:07
   --------------------------------- ------ 59.0/69.5 MB 1.6 MB/s eta 0:00:07
   ---------------------------------- ----- 59.2/69.5 MB 1.6 MB/s eta 0:00:07
   ---------------------------------- ----- 59.5/69.5 MB 1.6 MB/s eta 0:00:07
   ---------------------------------- ----- 59.8/69.5 MB 1.6 MB/s eta 0:00:07
   ---------------------------------- ----- 60.0/69.5 MB 1.6 MB/s eta 0:00:07
   ---------------------------------- ----- 60.3/69.5 MB 1.5 MB/s eta 0:00:06
   ---------------------------------- ----- 60.3/69.5 MB 1.5 MB/s eta 0:00:06
   ---------------------------------- ----- 60.6/69.5 MB 1.5 MB/s eta 0:00:06
   ---------------------------------- ----- 60.8/69.5 MB 1.5 MB/s eta 0:00:06
   ----------------------------------- ---- 61.1/69.5 MB 1.5 MB/s eta 0:00:06
   ----------------------------------- ---- 61.3/69.5 MB 1.5 MB/s eta 0:00:06
   ----------------------------------- ---- 61.6/69.5 MB 1.5 MB/s eta 0:00:06
   ----------------------------------- ---- 61.9/69.5 MB 1.5 MB/s eta 0:00:05
   ----------------------------------- ---- 62.1/69.5 MB 1.5 MB/s eta 0:00:05
   ----------------------------------- ---- 62.4/69.5 MB 1.5 MB/s eta 0:00:05
   ------------------------------------ --- 62.7/69.5 MB 1.5 MB/s eta 0:00:05
   ------------------------------------ --- 62.9/69.5 MB 1.5 MB/s eta 0:00:05
   ------------------------------------ --- 63.2/69.5 MB 1.5 MB/s eta 0:00:05
   ------------------------------------ --- 63.4/69.5 MB 1.5 MB/s eta 0:00:04
   ------------------------------------ --- 63.7/69.5 MB 1.5 MB/s eta 0:00:04
   ------------------------------------ --- 64.0/69.5 MB 1.5 MB/s eta 0:00:04
   ------------------------------------ --- 64.2/69.5 MB 1.5 MB/s eta 0:00:04
   ------------------------------------- -- 64.5/69.5 MB 1.5 MB/s eta 0:00:04
   ------------------------------------- -- 64.7/69.5 MB 1.5 MB/s eta 0:00:04
   ------------------------------------- -- 64.7/69.5 MB 1.5 MB/s eta 0:00:04
   ------------------------------------- -- 65.0/69.5 MB 1.5 MB/s eta 0:00:04
   ------------------------------------- -- 65.3/69.5 MB 1.5 MB/s eta 0:00:03
   ------------------------------------- -- 65.5/69.5 MB 1.5 MB/s eta 0:00:03
   ------------------------------------- -- 65.8/69.5 MB 1.5 MB/s eta 0:00:03
   -------------------------------------- - 66.1/69.5 MB 1.5 MB/s eta 0:00:03
   -------------------------------------- - 66.3/69.5 MB 1.5 MB/s eta 0:00:03
   -------------------------------------- - 66.6/69.5 MB 1.4 MB/s eta 0:00:03
   -------------------------------------- - 66.8/69.5 MB 1.4 MB/s eta 0:00:02
   -------------------------------------- - 67.1/69.5 MB 1.4 MB/s eta 0:00:02
   -------------------------------------- - 67.6/69.5 MB 1.4 MB/s eta 0:00:02
   ---------------------------------------  67.9/69.5 MB 1.4 MB/s eta 0:00:02
   ---------------------------------------  68.2/69.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  68.4/69.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  68.7/69.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  68.9/69.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 69.5/69.5 MB 1.4 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.3.0

In [2]:
import xgboost

In [3]:
import pandas as pd

In [4]:
dataset=pd.read_csv("insurance_pre.csv")

In [5]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [6]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [7]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [8]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [10]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [11]:
dependent=dataset[['charges']]

In [12]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [44]:
from sklearn.ensemble import GradientBoostingRegressor
regressor = GradientBoostingRegressor(loss='huber', learning_rate=0.1, n_estimators=100, subsample=1.0,criterion='squared_error', random_state=0)
regressor.fit(x_train, y_train)

C:\Anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:672: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

GradientBoostingRegressor(criterion='squared_error', loss='huber',
                          random_state=0)

In [45]:
y_pred=regressor.predict(x_test)

In [46]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [47]:
r_score

0.8914390761897757

In [48]:
import pickle
filename="Finalized_model_xgboost.sav"
pickle.dump(regressor,open(filename,'wb'))

In [49]:
loaded_model=pickle.load(open("Finalized_model_xgboost.sav",'rb'))
result=loaded_model. predict([[69,29,0,0,1]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(

In [50]:
result

array([29536.42347793])